import {api,postJson,DEFAULT_BOOK_TEXT,esc,usd,formatUtc} from "/lib.js";
import {heading,link,external,GITHUB,skeleton,errorState,empty,totals,allocations,receiptRow,notice,verification} from "/ui.js";
export const landingPage={
 title:"A clear plan for every payout",
 description:"Describe a monthly payout, review three recipient allocations, and prepare a receipt you can check. Demo only, no funds move.",
 render:()=>`<div class="landing-page"><section class="hero shell"><div class="hero-copy"><h1>One budget.<br>Everyone accounted for.</h1><p>Describe your payout. Review each person's share. Prepare a receipt you can check.</p><div class="hero-actions">${link("/app","Open payout book",true)}<a href="#receipt-proof">See receipt proof</a></div></div><aside class="hero-book" id="hero-book" aria-label="Live demo payout book">${skeleton("Loading the demo allocation")}</aside></section><div class="shell">${notice("Demo only. No funds move. Monthly allocations are prepared manually, not scheduled automatically.")}<section class="content-section"><h2>From a sentence to a clear record.</h2><p>For someone coordinating regular support or contractor payouts, the important questions are simple: who, how much, and what happened?</p><ol class="journey"><li><h3>Describe</h3><p>Write your payout in everyday language.</p></li><li><h3>Review</h3><p>Check the amounts and any corrections.</p></li><li><h3>Prepare</h3><p>Create unsigned payment requirements.</p></li><li><h3>Verify</h3><p>Keep a receipt and check its integrity.</p></li></ol></section><section class="content-section"><div class="section-heading"><h2>Three people. One monthly book.</h2><p>This demo uses a fixed $400 budget and three recipients. The default allocation is 80% to recipients and 20% excluded.</p></div><div id="landing-allocation">${skeleton("Loading recipients")}</div><p class="helper">The held amount is only recorded as excluded. Allot does not receive or hold money.</p></section><section class="content-section" id="receipt-proof"><h2>A record you can come back to.</h2><p>The newest preparation from this shared demo appears below. Download receipts you want to keep.</p><div id="latest-receipt">${skeleton("Loading receipt proof")}</div></section><section class="content-section boundary-grid"><div><h2>What happens here</h2><p>Your instruction becomes a checked allocation. Allot retrieves a Binance quote, prepares x402 requirements, and saves a hashed receipt.</p></div><div><h2>What does not happen</h2><p>No wallet credentials, signatures, broadcasts, or settlement. This is a payout preparation demo, not a live transfer service.</p></div></section><section class="content-section"><h2>Before you try it</h2><div class="faq-list">
 <details><summary>What is a payout book?</summary><p>A record of who an allocation is for, how much each person receives, and how often it is intended. Here, the recipients, budget, and monthly frequency are fixed.</p></details>
 <details><summary>Does the demo send money every month?</summary><p>No. Monthly is the intended allocation frequency. Each demonstration must be started manually, and no transfer occurs.</p></details>
 <details><summary>What does prepared mean?</summary><p>The information needed to request a payment exists. No wallet approved it and no recipient was paid.</p></details>
 <details><summary>What happens to the held amount?</summary><p>It is excluded from the payment requirements. There is no deposit, custody, lock, or automatic release.</p></details>
 <details><summary>What does verification prove?</summary><p>It checks whether the receipt content matches its printed hash. It does not establish sender identity, authenticity, or settlement.</p></details>
 <details><summary>Why can a receipt disappear?</summary><p>The demo stores receipts in a JSON file. Hosted temporary storage can reset after redeployment. Downloading a receipt preserves a readable copy.</p></details>
 <details><summary>Is Allot a trading bot?</summary><p>No. The quote is used to prepare a payout allocation, not to predict markets or place trades.</p></details></div></section><section class="final-cta"><div><h2>Start with one sentence.</h2><p>See what Allot understands before anything is prepared.</p></div>${link("/app","Open payout book",true)}</section></div></div>`,
 async mount({root,alive}){
  async function book(){
   const targets=[root.querySelector("#hero-book"),root.querySelector("#landing-allocation")];
   targets.forEach(target=>target.innerHTML=skeleton("Loading allocation"));
   try{const parsed=await postJson("/api/parse",{text:DEFAULT_BOOK_TEXT});if(!alive())return;
    targets[0].innerHTML=`<div class="preview-head"><h2>Monthly demo book</h2><strong>${usd(parsed.totals.gross_usd)}</strong></div><p>${usd(parsed.totals.spend_usd)} allocated to three people</p><div class="recipient-list">${parsed.allocation.filter(r=>r.role==="spend").map(r=>`<div class="recipient-row"><div><strong>${esc(r.name)}</strong><span>${esc(r.city)}</span></div><strong>${usd(r.usd)}</strong></div>`).join("")}</div><p class="preview-held">${usd(parsed.totals.hold_usd)} excluded from preparation</p>`;
    targets[1].innerHTML=allocations(parsed.allocation);
   }catch(error){if(alive()){targets.forEach((target,index)=>target.innerHTML=errorState("Demo book unavailable",error.message,"retry-book-"+index));root.querySelectorAll('[id^="retry-book-"]').forEach(button=>button.onclick=book);}}
  }
  async function latest(){
   const target=root.querySelector("#latest-receipt");
   try{const rows=await api("/api/receipts");if(!alive())return;
    if(!rows.length){target.innerHTML=empty("No receipts on this instance yet","Prepare the first payout to create a receipt.");return;}
    const r=rows[0];target.innerHTML=receiptRow(r)+'<p id="latest-check" role="status">Checking receipt integrity…</p>';
    const status=root.querySelector("#latest-check");
    try{const result=await api("/api/verify/"+encodeURIComponent(r.receipt_id));if(!alive())return;status.textContent=result.ok?"Receipt content matches its hash. No funds moved.":"Integrity warning: receipt content does not match its hash.";status.className=result.ok?"match-text":"field-error";if(!result.ok)status.setAttribute("role","alert");}
    catch{if(alive())status.innerHTML='Verification unavailable. <a href="/verify?value='+encodeURIComponent(r.receipt_id)+'" data-link>Try verification again</a>';}
   }catch(error){if(alive()){target.innerHTML=errorState("Receipt proof unavailable",error.message,"retry-proof");root.querySelector("#retry-proof").onclick=latest;}}
  }
  await Promise.all([book(),latest()]);
 }
};
export const howPage={
 title:"How it works",
 render:()=>`<div class="shell narrative-page">${heading("How Allot works","A payout preparation, explained from the sender's point of view.",link("/app","Open payout book",true))}
 <nav class="help-index" aria-label="On this page"><a href="#describe">Describe</a><a href="#review">Review</a><a href="#prepare">Prepare</a><a href="#verify">Verify</a></nav>
 <section class="story-block" id="describe"><div><h2>Describe the allocation</h2><p>Start with the fixed $400 monthly book. The three recipients and their relative shares are already defined. Tell Allot how much is for spending and how much to exclude.</p></div><div class="example-box"><strong>Try this</strong><code>${esc(DEFAULT_BOOK_TEXT)}</code><p>Weekly or daily schedules and recognized trading instructions are rejected. Missing values use clearly explained defaults. Unclear percentages need correction.</p></div></section>
 <section class="story-block" id="review"><div><h2>Check what Allot understood</h2><p>Review the original sentence alongside the accepted budget, split, and recipient amounts. If you entered a different budget, the fixed $400 amount is clearly shown before preparation.</p></div><div><h3>For the default allocation</h3><p>$320 goes into recipient requirements: $128 for Amara, $112 for Kwame, and $80 for Elena. The other $80 is excluded.</p><p>Held is bookkeeping language. No funds are deposited or locked.</p></div></section>
 <section class="story-block" id="prepare"><div><h2>Prepare, without sending</h2><p>Allot fetches a Binance USDCUSDT quote. The USD budget is treated as USDC-equivalent for this demo. It creates three x402 payment requirements and a stored receipt.</p></div><div><h3>What the rail tells you</h3><p>Price source and conversion amounts appear on the receipt. A quote failure blocks preparation. Optional Bazaar discovery failure becomes a warning.</p><p>The payload may reference BSC mainnet. This is an unsigned envelope, not a testnet or mainnet transfer. No wallet is connected.</p><p>Settlement fees and local-currency cash-out are not estimated.</p></div></section>
 <section class="story-block" id="verify"><div><h2>Keep and check the receipt</h2><p>Open a receipt from activity, download its JSON, copy its link, or print it. Verification recomputes a SHA-256 hash of the stored receipt content.</p></div><div><h3>Match does not mean paid</h3><p>The hash checks content consistency. It is not a digital signature and does not prove sender identity, authenticity, or blockchain settlement.</p><p>Hosted storage is temporary. A downloaded file remains readable after an instance reset; online lookup may no longer work.</p></div></section>
 <section class="content-section"><h2>Common problems</h2><div class="faq-list"><details><summary>My instruction was corrected</summary><p>The budget, recipients, and frequency are fixed. Review each warning. Edit the sentence if the accepted instruction is not what you intend. Unclear percentages cannot proceed.</p></details><details><summary>Pricing failed</summary><p>Try preparing again later. A successful quote is required before payment requirements can be created.</p></details><details><summary>The request timed out</summary><p>Check activity first. A server may have saved a receipt even when the browser missed its response. Retrying the same attempt uses the same request identifier while this page session remains open.</p></details><details><summary>A receipt is missing</summary><p>Check the ID and current demo instance. Storage may have reset. Use your downloaded copy for a readable record.</p></details></div></section>
 <section class="final-cta"><h2>Review your first allocation.</h2>${link("/app","Open payout book",true)}</section></div>`
};
export const writeupPage={
 title:"Build notes",
 render:()=>`<div class="shell narrative-page">${heading("Build notes","Implementation details for teammates, reviewers, and hackathon judges.",external(GITHUB,"View repository"))}<div class="prose">
 <section><h2>A payments use case for non-traders</h2><p>Allot explores agent-assisted payout preparation. One plain-English instruction becomes a fixed three-recipient allocation, unsigned x402 requirements, and a verifiable receipt.</p></section>
 <section><h2>Working product surfaces</h2><p>The book overview provides context, the guided workspace handles describe and review, activity stores preparation history, and receipt pages combine outcomes with expandable technical evidence.</p><p>Draft text stays in session storage when available. Receipts are server-side JSON, shared by this demo instance. There are no user accounts or database.</p></section>
 <section><h2>Parser and agent interface</h2><p>A deterministic parser recognizes supported money, monthly cadence, and labelled spend/held percentages. It is not a general-purpose language model. Invalid or ambiguous splits are rejected. Server-side decimal arithmetic produces the review allocation and execution amounts.</p><p>The website uses HTTP APIs. MCP tools call the same parser, execution, lookup, and verification functions.</p></section>
 <section><h2>Rail integration</h2><p>The rail fetches a Binance USDCUSDT quote, using spot testnet with a public mainnet ticker fallback. It builds x402 v2 exact-scheme requirements for BSC USDT and records optional Bazaar discovery evidence.</p><p>GET payout endpoints return HTTP 402 and PAYMENT-REQUIRED. Requests with PAYMENT-SIGNATURE are rejected. There is no signing, broadcasting, settlement, or automatic monthly scheduler.</p></section>
 <section><h2>API reference</h2><dl class="api-reference"><dt>GET /api/book</dt><dd>Fixed payout configuration</dd><dt>POST /api/parse</dt><dd>Instruction, validation, warnings, and decimal-calculated allocation</dd><dt>POST /api/execute</dt><dd>Prepare unsigned requirements and store a receipt</dd><dt>GET /api/receipts</dt><dd>Shared demo history</dd><dt>GET /api/receipts/{id-or-hash}</dt><dd>Canonical stored receipt</dd><dt>GET /api/verify/{id-or-hash}</dt><dd>Claimed and recomputed hashes</dd><dt>GET /api/health</dt><dd>Current quote and optional discovery availability</dd><dt>GET /healthz</dt><dd>Lightweight service health</dd><dt>GET /payout/{receipt_id}/{recipient_id}</dt><dd>HTTP 402 payment requirement</dd></dl></section>
 <section><h2>Teammate integration contract</h2><p>The interface consumes receipt_id, issued_at, status, instruction, quote, legs, totals, evidence, bazaar, receipt_hash, and what_remains. A failed quote returns ok: false and retryable: true. Discovery failure is non-blocking.</p><p>Rail outputs are shown as returned. The website does not invent transaction hashes, fees, wallet approvals, or settlement status.</p></section>
 <section><h2>Verification boundaries</h2><p>SHA-256 is computed from canonical receipt JSON excluding receipt_hash. Matching content and hash demonstrates consistency only. Anyone able to change both can recompute a hash; this is not signed authentication.</p></section>
 <section><h2>Run and test locally</h2><pre>python -m allot serve</pre><p>No npm installation or frontend build is required.</p><pre>python -m unittest discover -s tests -v</pre><p>Regression tests cover parsing, exact allocations, receipt hashing, public routes, and HTTP payment boundaries. See the repository for executable tests and the latest results.</p></section>
 </div></div>`
};

